### ISSUE TITLE
Can't draw anything on canvas (Vue)

### ISSUE THREAD

**Issue by sebj54** [triniwiz/nativescript-canvas-plugin#12]
### Description

Canvas is totally filled with black, anything I try to draw remains invisible.

### Which platform(s) does your issue occur on?

- Android (iOS not tested yet)
- Real device (Xiaomi A1, Android 10)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): 6.5.0
- Plugin(s): 

```json
{
  "dependencies": {
    "@vue/devtools": "^5.3.3",
    "dotenv": "^8.2.0",
    "nativescript-canvas-plugin": "^0.4.1",
    "nativescript-sentry": "^1.9.1",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-vue": "^2.6.1",
    "nativescript-vue-devtools": "^1.4.0",
    "tns-core-modules": "^6.5.1",
    "vuex": "^3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@vue/cli-plugin-eslint": "^4.3.1",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-loader": "^8.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "nativescript-dev-webpack": "^1.5.1",
    "nativescript-vue-template-compiler": "^2.6.0",
    "nativescript-worker-loader": "~0.11.0",
    "node-sass": "^4.13.1",
    "vue-loader": "^15.9.1"
  },
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 

main.js
```js
Vue.registerElement('Canvas', () => require('nativescript-canvas-plugin').TNSCanvas)
```

App.vue
```vue
<template>
    <Page>
        <ActionBar
            title="Welcome to NativeScript-Vue!"
            android:flat="true"
        />

        <GridLayout
            columns="*"
            rows="*"
        >
            <canvas
                col="0"
                row="0"
                @layoutChanged="loaded($event)"
            />
        </GridLayout>
    </Page>
</template>

<script >
export default {
    methods: {
        loaded({ object }) {
            const canvas = object
            const ctx = canvas.getContext('2d')

            ctx.beginPath()
            ctx.fillStyle = 'red'
            ctx.arc(150, 75, 50, 0, 2 * Math.PI)
            ctx.fill()
            ctx.closePath()
        }
    }
}
</script>
```

### Is there any code involved? 

I can provide a zip if you cannot reproduce.

Thanks for your help!

**Comment by triniwiz** [comment]
Hi can you try wrapping that in loaded event in a time ~3secs to be sure ... I think I know what’s the cause already

**Comment by sebj54** [comment]
Hi @triniwiz, thanks for your answer!

I tried several things:

- Change @layoutChanged event for a @loaded event
- In the loaded method of my component, try to draw on canvas after 3 seconds (with `setTimeout`)
- Mount canvas component after 3 seconds
- Use canvas on another page (not the first one)
- Change what I try to draw (I have tried to use the example in the README file)

None of these attempts have worked: canvas is still totally black.

Let me know if I can try something else!

**Comment by sebj54** [comment]
Thanks for the updated version @triniwiz!

Unfortunately, this does not seem to work more than the previous version. I updated the plugin, deleted `platforms`, `hooks` and `node_modules`, made a fresh install of my app. I also changed `layoutChanged` event for `ready`.

Canvas stay transparent now, nothing is drawn.

Do you want me to provide you code for a sample Vue app?

**Comment by triniwiz** [comment]
@sebj54 i'll throw in a vue demo 😃

**Comment by sebj54** [comment]
@triniwiz This works well now! Canvas is always displayed, I had nothing to change in my app, just needed to update. Thanks!

I don't know if it is related to HMR but when I reduce the app (by hitting the home button) and resume my app, canvas disappears. Maybe I should use another event to redraw everything?

**Comment by triniwiz** [comment]
It could be related to hmr try `—no-hmr` when running tns

**Comment by sebj54** [comment]
Even with `--no-hmr`, the canvas disappears.
