### ISSUE TITLE
Implement isPointInPath

### ISSUE THREAD

**Issue by sebj54** [triniwiz/nativescript-canvas-plugin#22]
I just finished to set up my France map, started to implement click on regions and I saw that `isPointInPath` has not been implemented yet 😅 

It would be a really great addition! 

I tried to use `addRegionPath` but same problem. 

I assume it is a hard task so feel free to give me directions if I can help you somehow.
Thanks again for your very interesting plugin, it is very powerful!

**Comment by triniwiz** [comment]
It's sort of a long process
1. Port [this](https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/canvas2d/CanvasRenderingContext2D.cpp#1092) to rust lib [here](https://github.com/triniwiz/canvas-native) would be added to common then expose it to [ios](https://github.com/triniwiz/canvas-native-ios) & [android](https://github.com/triniwiz/canvas-native-android)
2. Build rust lib (atm my custom build file is not added to the repo)
3. implement newly added methods to [ios](https://github.com/triniwiz/canvas-native-ios) & [android](https://github.com/triniwiz/canvas-native-android)
4. build & release to cocoapods & jcenter 
5. implement new methods in {N}
6. Profit 😂

**Comment by sebj54** [comment]
I see, it is not as simple as I thought 😅 

Unfortunately, I don't know Rust nor C++ so I'm not sure I can help finally...

**Comment by triniwiz** [comment]
I’m about to release this.

**Comment by sebj54** [comment]
Thank you very much @triniwiz, it works perfectly 👌

**Comment by triniwiz** [comment]
Feel free to share any screenshots 😂 #justCurious

**Comment by sebj54** [comment]
I'll do! I'm actually doing the second step (showing departments after a click on a region), it will be more interseting after that 😄

**Comment by sebj54** [comment]
Here is a video screenshot!

https://gofile.io/d/foVUem

It lacks some feedback for the user: highlight selected region, animations between regions and departments… Maybe in the future! 😁

**Comment by triniwiz** [comment]
Looking good a few improvements coming soon 🙂

**Comment by sebj54** [comment]
@triniwiz, I have actually an issue on iOS with isPointInPath. It is working fine with Android, but with iOS there is a ratio applied to x and y coordinates.

I listen on `tap` events and get x and y with `$event.getX() * screen.mainScreen.scale`.

Is it enough? Or should I apply another multiplicator on these values?
Thanks for your help!

**Comment by sebj54** [comment]
Very weird but I had to use `Math.pow(screen.mainScreen.scale, 2)` (on iOS only) to make it work. Maybe the device ratio is used as a divider somewhere?

**Comment by triniwiz** [comment]
Seems to be a measurement issue try [this](https://github.com/triniwiz/nativescript-canvas-plugin/blob/master/demo/app/home/home-page.xml#L9-L10)

**Comment by sebj54** [comment]
Unfortunately my canvas is already in a GridLayout. I really have to multiply the screen scale (on iOS) to make it work.

**Comment by triniwiz** [comment]
It will be fixed in the next release 😄
