### ISSUE TITLE
 Canvas flickering on updating for real device

### ISSUE THREAD

**Issue by dukewan** [triniwiz/nativescript-canvas-plugin#34]
# Which platform(s) does your issue occur on?
- iOS
- iOS 13
- emulator or device. What type of device?
Only device, iPhone Xs. Emulator works fine.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.8
- Cross-platform modules: 6.5.8
- Runtime(s): 6.5.1
- Plugin(s):
```
 "dependencies": {
    "@nativescript/theme": "^2.2.1",
    "@nstudio/nativescript-camera-plus": "^3.0.7",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@vue/devtools": "^5.3.3",
    "axios": "^0.19.2",
    "bson-objectid": "^1.3.1",
    "lodash": "^4.17.15",
    "moment": "^2.27.0",
    "nativescript-akylas-fonticon": "^2.0.7",
    "nativescript-camera": "^4.5.0",
    "nativescript-canvas-plugin": "^0.8.0",
    "nativescript-clipboard": "^1.2.0",
    "nativescript-cscreenshot": "^1.0.2",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-keyboard-toolbar": "^1.1.0",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-social-share-knotes": "^1.6.0",
    "nativescript-socketio": "^3.3.1",
    "nativescript-sqlite": "^2.6.3",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-vue": "~2.4.0",
    "nativescript-vue-devtools": "^1.4.0",
    "nativescript-vue-shadow": "^0.1.0",
    "nativescript-windowed-modal": "^6.2.1",
    "tns-core-modules": "^6.5.8",
    "vuex": "^3.4.0",
    "vuex-i18n": "^1.13.1"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-html": "^6.0.2",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-vue": "^6.2.2",
    "nativescript-dev-webpack": "~1.5.1",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.14.1",
    "vue-loader": "~15.4.0"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1. Init a nativescript-vue project
2. Install `nativescript-canvas-plugin`
3. Create a new canvas
4. Either setTimeout in `ready` method to update canvas, or handle `@touch` to update canvas
5. Install the app in real ios device, try touch the canvas to see the flickering
![ezgif-3-4fc192f19269](https://user-images.githubusercontent.com/2100515/87127569-f3ac3200-c242-11ea-8e84-54f649e8524d.gif)

### Is there any code involved? 
 Template:
```
 <TNSCanvas id="canvas" iosOverflowSafeArea="true" col="0" row="0" @ready="canvasReady" @touch="onCanvasTouch2" width="400" height="400"
            />
```

Js:
```
canvasReady ({ object }) {
      const canvas = object
      const ctx = canvas.getContext('2d')
      ctx.beginPath()
      ctx.fillStyle = 'red'
      ctx.arc(150, 75, 50, 0, 2 * Math.PI)
      ctx.fill()
      ctx.closePath()
      this.ctx = ctx
    },
    onCanvasTouch2 () {
      this.ctx.beginPath()
      this.ctx.moveTo(100 * Math.random(), 100 * Math.random())
      this.ctx.lineTo(400 * Math.random(), 400 * Math.random())
      this.ctx.strokeStyle = 'blue'
      this.ctx.strokeWidth = 40
      this.ctx.stroke()
      this.ctx.closePath()
    },
```

**Comment by triniwiz** [comment]
I’ll look into this but you should use the `requestAnimationFrame`

**Comment by dukewan** [comment]
Thanks for looking! I just tried `requestAnimationFrame` with no luck:

```
onCanvasTouch2 (args) {
      requestAnimationFrame(() => {
        this.ctx.beginPath()
        this.ctx.moveTo(100 * Math.random(), 100 * Math.random())
        this.ctx.lineTo(400 * Math.random(), 400 * Math.random())
        this.ctx.strokeStyle = 'blue'
        this.ctx.strokeWidth = 40
        this.ctx.stroke()
        this.ctx.closePath()
      })
}
```

Btw, the background color of canvas differs between emulator and real device. Device reflect the transparent that I set while emulator has yellow background.

**Comment by triniwiz** [comment]
I noticed that will try fixing for next release also what device are you testing on (mine is usually a 11 Pro Max)

**Comment by triniwiz** [comment]
oh one thing you can do is 
```ts
canvasReady ({ object }) {
      const canvas = object
      canvas.nativeView.handleInvalidationManually = true;
      const ctx = canvas.getContext('2d')
      ctx.beginPath()
      ctx.fillStyle = 'red'
      ctx.arc(150, 75, 50, 0, 2 * Math.PI)
      ctx.fill()
      canvas.flush();
      ctx.closePath()
      this.ctx = ctx
    },
    onCanvasTouch2 () {
      this.ctx.beginPath()
      this.ctx.moveTo(100 * Math.random(), 100 * Math.random())
      this.ctx.lineTo(400 * Math.random(), 400 * Math.random())
      this.ctx.strokeStyle = 'blue'
      this.ctx.strokeWidth = 40
      this.ctx.stroke()
      this.ctx.canvas.flush();
      this.ctx.closePath()
    },

```

it my little way of allowing the flush (draw to screen) manually instead of the `CADisplayLink`

**Comment by dukewan** [comment]
The new attempt improves a bit, we don't have the white background while flickering now. But the flickering still exists.

Looking at the gif that I attached, it seems there are two different canvas layers, the toggling between these two canvas make it look flickering. 

I use iPhone Xs for testing.

**Comment by triniwiz** [comment]
Can you try [this](https://github.com/triniwiz/nativescript-canvas-plugin/blob/master/demo/app/home/home-page.ts) tap the screen or touch and drag LMK how it looks (dragging for long you may notice a slow down the final updates to start 1.x should improve that)

**Comment by dukewan** [comment]
It seems to have the same issue.

**Comment by triniwiz** [comment]
This should not be an issue with the latest release which has been moved to a [new home](https://github.com/NativeScript/canvas) feel free to open an issue if it's still not working as you like
