### ISSUE TITLE
NativeScript 7 and Angular 10 issue

### ISSUE THREAD

**Issue by MartinPenev** [triniwiz/nativescript-canvas-plugin#40]
### If the demo apps cannot help and there is no issue for your problem, tell us about it

First of all - Thank you for the wonderful plugin!
Now about the issue - we are unable to use it with the new NativeScript 7 and Angular 10. According to this thread - https://github.com/NativeScript/NativeScript/issues/8757 - most likely the error happens because it targets ES5. 

Here is the error:

ERROR in node_modules/nativescript-canvas-plugin/angular/index.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-canvas-plugin/angular) which declares TNSCanvasModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class TNSCanvasModule {
...

### Which platform(s) does your issue occur on?
- iOS/Android/Both - Both
- iOS/Android versions 
- emulator or device. What type of device? - All

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Use it in NS7 and Angular 10

**Comment by triniwiz** [comment]
This is currently in progress 🙂

**Comment by MartinPenev** [comment]
Thanks! :+1:

**Comment by triniwiz** [comment]
Moved to a [new home](https://github.com/NativeScript/canvas) `@nativescript/canvas`
