### ISSUE TITLE
Is it possible to install this plugin on Angular?

### ISSUE THREAD

**Issue by bellalMohamed** [triniwiz/nativescript-canvas-plugin#6]
Is it possible to install this plugin on Angular?
I tried to use it with angular but I didn't manage to initiate the TNSCanvas class

**Comment by triniwiz** [comment]
Have you tried registering the element ? 

```ts
registerElement('Canvas', () => require('nativescript-canvas-plugin').TNSCanvas);
```

**Comment by triniwiz** [comment]
@bellalMohamed all you need to do is https://github.com/triniwiz/nativescript-canvas-plugin/blob/master/demo-angular/src/main.ts#L5
